language: node_js
node_js:
 - "node"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: lint
      script: eslint **/*.js
    - stage: test
      script: npm run cover
    - stage: bundle
      script: rollup -c
stages:
  - lint
  - test
  - bundle
after_success: 'npm run coveralls'